# Generated by Django 4.2.1 on 2023-05-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.CharField(
                choices=[("Manager", "Manager"), ("Employee", "Employee")],
                default="Employee",
                max_length=20,
            ),
        ),
    ]
